name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "merit-award" #Must be unique in Heroku
          heroku_email: "rishabjsluthra@gmail.com"
          usedocker: true
          docker_build_args: |
            dbpass
        env:
          dbpass: ${{ secrets.AWS_PASSWORD }}