name: Run tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  react-tests:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./client
      run: npm i
    - name: Run tests
      working-directory: ./client
      run: npm test
  go-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Run tests
      working-directory: ./server
      run: go test ./...